source 'https://rubygems.org'

gem 'rails', '4.2.1'
gem "rails-api"

# Authentication
gem 'cancancan'
gem 'devise'

# Database
gem "pg"

# Requests
gem "rack-cors", require: "rack/cors"

# Search
gem "pg_search"

# Serialization
gem "active_model_serializers"

group :development, :test do

end

